### ISSUE TITLE
Can't find main.py when using the action from a different repo

### ISSUE THREAD

**Issue by dwsilk** [jacobtomlinson/python-container-action#1]
Thanks for the template and write-up!

I created https://github.com/dwsilk/lds-feed-action based on this and every thing seems great until I attempt to use the action in a different repository: https://github.com/dwsilk/test-lds-feed-action/runs/454024036?check_suite_focus=true

I then get `/usr/bin/python3.7: can't open file 'main.py': [Errno 2] No such file or directory` which doesn't occur via the integration tests.

I also get the same result when attempting to use your yaml linting action (https://github.com/jacobtomlinson/gha-lint-yaml), which is also based on this template: https://github.com/dwsilk/test-lds-feed-action/runs/454041682?check_suite_focus=true

Is it something to do with path setup in the Dockerfile?

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I'm not sure why this is happening. The Dockerfil builds correctly for me locally.

I wonder if switching this line to explicitly be `COPY main.py /app/main.py` might help?
https://github.com/jacobtomlinson/python-container-action/blob/b77ee691c4fc8f6023b1e16937856e18ea509ef6/Dockerfile#L2

**Comment by dwsilk** [comment]
I tried (https://github.com/dwsilk/test-lds-feed-action/runs/455045934?check_suite_focus=true#step:2:32), unfortunately same result.

**Comment by jacobtomlinson** [comment]
Hmm thanks for trying. What about also explicitly setting the `CMD` to be `/app/main.py`?

**Comment by dwsilk** [comment]
Yes! :tada: https://github.com/dwsilk/test-lds-feed-action/runs/455070824?check_suite_focus=true#step:2:115

**Comment by jacobtomlinson** [comment]
Hmm that is frustrating! We are setting the `WORKDIR` to `/app` so a relative path should work.

Would you mind raising a PR to fix the template?

**Comment by dwsilk** [comment]
Sure, done. Thanks for the quick response, it's great to have this working. :+1:

**Comment by jacobtomlinson** [comment]
Thanks for the PRs. The blog post probably also needs updating. I think it's probably [just this section](https://github.com/jacobtomlinson/jacobtomlinson.github.io/blob/master/content/posts/2019/2019-12-09-creating-github-actions-in-python.md#dockerfile) that needs updating, but as you've read it recently could you just confirm?

**Comment by dwsilk** [comment]
Yep, I think that's it, plus one other small but unrelated detail.
